[package]
name = "multiset"
version = "0.1.0"
repository = "https://github.com/jmitchell/multiset"
description = "Multisets/bags"
keywords = ["multiset","bag","data-structure","collection","count"]
license = "MIT/Apache-2.0"
authors = ["Jake Mitchell <jacob.d.mitchell@gmail.com>"]
